version: '3.8'
services:
    arches_db:
      container_name: arches_db
      image: postgis/postgis:13-3.2
      volumes:
          - postgres-data:/var/lib/postgresql
          - postgres-log:/var/log/postgresql
          - ./init-unix.sql:/docker-entrypoint-initdb.d/init.sql # to set up the DB template
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgis
        - POSTGRES_DB=postgres
        - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology
        - TZ=PST
      networks:
        - arches_dev

    arches_couchdb:
      container_name: arches_couchdb
      image: couchdb:2.1.1
      ports:
        - "5984:5984"
      volumes:
        - couchdb-data:/usr/local/var/lib/couchdb
        - couchdb-log:/usr/local/var/log/couchdb
      environment:
        - COUCHDB_USER=admin
        - COUCHDB_PASSWORD=password
      networks:
        - arches_dev

    arches_elasticsearch:
      container_name: arches_elasticsearch
      image: elasticsearch:7.9.2
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - TZ=PST
        - discovery.type=single-node
        - discovery.seed_hosts=
        - "ES_JAVA_OPTS=-Xms400m -Xmx400m"
      networks:
        - arches_dev

    arches_rabbitmq:
      container_name: arches_rabbitmq
      image: rabbitmq:3-management
      hostname: my-rabbit
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - rabbitmq-logs:/var/log/rabbitmq/log
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - arches_dev

networks:
  arches_dev:
    name: arches_dev
    driver: bridge

volumes:
    couchdb-data:
    couchdb-log:
    postgres-data:
    postgres-log:
    elasticsearch-data:
    rabbitmq-logs:
    rabbitmq-data:
